<?php

/**
 * @file
 * Provides an integration for the JQScribble library for Drupal.
 */

/**
 * Implements hook_menu().
 *
 * @return mixed
 */
function scribble_menu() {
  $items['blackboard'] = array(
    'title' => 'Scribble blackboard',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scribble_blackboard_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'scribble.pages.inc',
  );
  /*
  $items['admin/config/user-interface/scribble'] = array(
    'title' => 'Example RSS feed',
    'page callback' => 'example_feed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  */

  return $items;
}

/*
 * Implements hook_library().
 */
function scribble_library() {
  // @todo add canvas bgimage path and add saveurl as settings
  $libraries['jqscribble'] = array(
    'title' => t('JQScribble'),
    'website' => 'https://github.com/jimdoescode/jqScribble',
    'version' => '1.0',
    'js' => array(
      libraries_get_path('jqscribble') . '/jquery.jqscribble.js' => array(
        'type' => 'file',
      ),
      libraries_get_path('jqscribble') . '/jqscribble.extrabrushes.js' => array(
        'type' => 'file',
      ),
      drupal_get_path('module', 'scribble') . '/scribble.js' => array(
        'type' => 'file',
      ),
    ),
    'css' => array(
      drupal_get_path('module', 'scribble') . '/scribble.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

